jquery/jquery.com

pages/download.md
We now have `compat` & `master` branches and we no longer support IE<8. Also,
links to the pre-release files have changed.
cc @dmethvin
=> Download: Update the "jQuery Pre-Release Builds" section

pages/index.html
Sizzle does not have a certificate so when the link goes to https://sizzlejs.com it is broken.
=> Index: Fix Sizzle link to always use http

pages/browser-support.html
Opera is now just another Chromium-based browser, like Yandex.Browser.
It doesn't make sense to test on two Opera versions.
cc @jquery/core as this needs to be officially decided by the team (this is just my proposal)
=> Browser support: Test only on latest Opera

pages/index.html
Opera is now a secondary browser (as one of Chromium-likes),
Edge is a main one. Also, the list is now sorted alphabetically.
=> Index: Update the browsers list

pages/download.md
Fixes #122 
Screenshot: <img width="969" alt="screen shot 2016-03-09 at 11 56 51" src="https://cloud.githubusercontent.com/assets/1758366/13633231/101af0a6-e5ee-11e5-8d4e-09ed5f975631.png">
The Bower section looks really similar now; perhaps we should simplify it now that it's not a recommended way to get jQuery? We could change it to a simple mention and redirect people to Bower docs for more info (e.g. target directory). Thoughts?
=> Download: Add a "Downloading jQuery using npm" section

pages/upgrade-guide/3.0.md
I forgot all about rejection handlers returning _fulfillment_ values until seeing it mentioned in the draft 3.0 RC announcement.
=> Docs: Document Deferred rejection callback return value handling

package-lock.json, pages/index.html
I also commited the generated `package-lock.json`. Any thoughts about that, @jquery/content?
This needs to be reviewed/landed together with https://github.com/jquery/jquery-wp-content/pull/405.
Screenshot:
=> Index: Add a no support notice for 1.x/2.x versions under Download

pages/browser-support.html
As discussed at the last meeting.
Please review @jquery/core.
=> Browser support: Document Firefox ESR support

pages/upgrade-guide/3.0.md
Fixed a small error in the upgrade guide.
It said "... and these **may may** not be integers...".
=> Remove duplicate "may"

pages/browser-support.html
Workarounds for Android Browser 4.0-4.3 are present in the code base but
we no longer actively test these versions.
=> Browser support: Update Android Browser support status

pages/upgrade-guide/3.5.md
Advise to use the new API:
```js
jQuery.migrateEnablePatches( "self-closed-tags" );
```
instead of the deprecated one:
```js
jQuery.UNSAFE_restoreLegacyHtmlPrefilter();
```
Also, fix some grammar mistakes & typos.
=> Upgrade guide: Use the new Migrate API to enable the self-closed-tags patch

pages/browser-support.html
We had to drop iOS 7 testing as iOS simulators are no longer supported
by BrowserStack and there are no real devices for iOS <10. We continue
to rely on old iOS emulators for testing as long as they work. iOS 8.3 & 9.3
seem to work fine for now but iOS 7.0 was breaking a lot; right now, the
browser doesn't even start.
Before:
After:
=> Browser support: Indicate iOS 7 is no longer tested

pages/browser-support.html, pages/download.md
It's not secure to install browsers from a third-party site that's only
available via insecure HTTP. Besides, with most browsers updating quickly
nowadays, there are not that many reasons to test on very old versions of most
browsers.
Therefore, let's just remove oldversion.com mentions without a replacement.
Ref gh-212
=> Browser support:Download: Drop mentions of oldversion.com

pages/browser-support.html, pages/download.md
Microsoft no longer provides such images.
Also, update `code.jquery.com` to `releases.jquery.com` in a few places and update the Google & Microsoft CDN links.
=> All: Remove mentions of MS-provided Windows images with IE

pages/license.md
* Imported from https://github.com/jquery/jquery.org/tree/d6d5143291598324d7888c70c9db482dd3046336/pages
* Tweaked slightly to refer to OpenJS Foundatoin instead of JS Foundation.
Ref https://github.com/jquery/jquery.org/issues/139
=> License page

pages/support.md
Inspired by these existing pages:
* https://jquery.org/support/ Imported from https://github.com/jquery/jquery.org/tree/d6d5143291598324d7888c70c9db482dd3046336/pages
* https://jqueryui.com/support/ Imported from https://github.com/jquery/jqueryui.com/pull/204
* https://learn.jquery.com/contributing/#getting-help
* https://brand.jquery.org/press-contact/ Recently changed in https://github.com/jquery/brand.jquery.org/pull/25
* https://irc.jquery.org/#current-channels
* https://meetings.jquery.org/#join
@timmywil If you like this, I would propose that we redirect `jquery.org/support/` here (https://github.com/jquery/jquery.org/issues/139). The others could either also redirect or perhaps be condensed in favour of a reference to this page. What do you think?
=> Support: New page

pages/index.html
The "Resources" section felt a bit lost on the home page due to the large padding and lack of block styling on its heading. It used to have a custom styling via `id="sidebar"` which was similar to a block, but was lost at some point without replacement. https://web.archive.org/web/20130301123913/jquery.com
Change it to a proper `<h2 class="block">` to look more on par with the rest of the page, and also remove the `padding-left: 60px` from the .resources class which is redundant now.
Also:
* remove outdated "About the jQuery Foundation" link.
* remove "Other Related Projects" section, which used low-quality images, was broken on mobile, loaded an extra copy of these logos on the home page, gave high-prominence to deprecated jQuery Mobile, and maintenance-only jQuery UI, used an outdated …
=> Index: restore "Resources" block style, remove JQF/Other projects

pages/download.md
* Enable the h1 heading. The page content has no custom h1 of its own so looks out of place with other pages on jquery.com.
* Invert the order of some paragraphs so that links are clear and at the top, with a single recommended option each time and then other links in a bullet list after it.
E.g. there is now an actual "Download jQuery 3.7.1" button, describing over top that it is the compressed production version, and then a list of other links.
Explanations of these files now follow the list instead of being in front of it, thus burying the links less.
* Promote link to browse releases.jquery.com to the first section.
I've personally never used the links that were in the first section previously as they always felt like too much text to read. When I land on the releases list, I know …
=> Download: enable h1, reduce decisions, remove old info

pages/download.md, pages/index.html, pages/support.md, pages/upgrade-guide.md
- Added banner message to index frontmatter (supported by https://github.com/jquery/jquery-wp-content/pull/468)
- Edited support messaging in and near download button
- Improved responsiveness of download button
- Added HeroDevs edits to support page
Ref https://github.com/jquery/jquery-wp-content/issues/462
Ref https://github.com/jquery/jquery.com/pull/245
Closes https://github.com/jquery/jquery.com/issues/243
=> Add Hero Devs support

pages/license.md
The old link broke at some point, and searching CC0 on tldrlegal now brings you to the current URL.
=> license: Fix link to the CC-0 license

pages/upgrade-guide/1.9.md, pages/upgrade-guide/3.0.md
Also, adjust code formatting in upgrade guides to match the jQuery code style.
=> Upgrade guide: Don't use deprecated AJAX event aliases
